//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP2016ProjectNew {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsMaze : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsMaze defaultInstance = ((SettingsMaze)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsMaze())));
        
        public static SettingsMaze Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ThreadsNum {
            get {
                return ((int)(this["ThreadsNum"]));
            }
            set {
                this["ThreadsNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BFS")]
        public string Algorithm {
            get {
                return ((string)(this["Algorithm"]));
            }
            set {
                this["Algorithm"] = value;
            }
        }
    }
}
